---
- name: Configure host
  hosts: all

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.docker
      become: true

  tasks:
    - import_tasks: tasks/apt-packages.yml
    - import_tasks: tasks/homebrew.yml
    - name: Create folder to hold AppImages
      ansible.builtin.file:
        path: "{{ ansible_env['HOME']}}/Apps"
        state: directory
    - name: Install AppImages
      include_tasks: tasks/appimage.yml
      loop: "{{ app_images }}"
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/git.yml
    - name: Change user shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ ansible_env['USER'] }}"
        shell: /bin/zsh
