---
- name: Configure host
  hosts: all

  vars_files:
    - config.yml

  tasks:
    - import_tasks: tasks/apt-packages.yml
    - import_tasks: tasks/homebrew.yml
    - import_tasks: tasks/obsidian.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/git.yml
    - name: Change user shell to zsh
      become: true
      ansible.builtin.user:
        name: "{{ ansible_env['USER'] }}"
        shell: /bin/zsh
