---
- name: Configure host
  hosts: all

  vars_files:
    - config.yml

  pre_tasks:
    - name: Add paths to PATH
      ansible.builtin.lineinfile:
        path: /etc/paths
        line: "{{ item }}"
      loop:
        - /Users/benpoppy/Library/Python/3.9/bin
        - /opt/homebrew/bin

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
    # - role: geerlingguy.mac.dock

  tasks:
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/git.yml
    - name: Set the global email value
      community.general.git_config:
        name: user.email
        scope: global
        value: bpoppy@intellum.com
    - name: Set email for personal repos
      community.general.git_config:
        name: user.email
        repo: "{{ home }}/{{ item }}"
        scope: local
        value: me@benpoppy.dev
      loop: "{{ git_personal }}"
