---
- name: Configure host
  hosts: all

  vars_files:
    - config.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
    # - role: geerlingguy.mac.dock

  tasks:
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/git.yml
