---
- name: Add wezterm repository
  become: yes
  block:
    - name: Install the wezterm gpg key
      ansible.builtin.get_url:
        url: https://apt.fury.io/wez/gpg.key
        dest: /etc/apt/trusted.gpg.d/wezterm-fury.asc
        mode: '644'
        force: yes

    - name: Add wezterm apt repository
      ansible.builtin.apt_repository:
        repo: deb https://apt.fury.io/wez/ * *
        filename: wezterm
        state: present

- name: Install apt packages
  become: yes
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ apt_installed_packages }}"
